// Generated by `pnpm ipc:generate`. Do not edit.

export type IpcErrorCodeDto = "invalid-request" | "invalid-job-id" | "job-not-found" | "invalid-job-state" | "tools-unavailable" | "analysis-failed" | "analysis-cancelled" | "persistence-unavailable" | "shutting-down" | "destination-selection-failed" | "reveal-failed" | "internal";

export type ErrorDetailDto = {
/**
 * Stable detail key.
 */
key: string,
/**
 * Bounded safe value.
 */
value: string, };

export type IpcErrorDto = {
/**
 * Stable machine code.
 */
code: IpcErrorCodeDto,
/**
 * Safe user-facing explanation.
 */
message: string,
/**
 * Optional structured safe context.
 */
details: Array<ErrorDetailDto>, };

export type BootstrapHealthDto = "healthy" | "degraded" | "failed";

export type ToolNameDto = "yt-dlp" | "ffmpeg" | "ffprobe" | "deno";

export type ToolSourceDto = "explicit-override" | "managed-update" | "bundled-baseline" | "development-path";

export type ToolStatusDto = {
/**
 * Tool identity.
 */
tool: ToolNameDto,
/**
 * Whether a verified executable is ready.
 */
ready: boolean,
/**
 * Selected verified tier.
 */
source: ToolSourceDto | null,
/**
 * Safe remediation message when unavailable.
 */
message: string | null, };

export type ThumbnailDto = {
/**
 * Validated HTTP(S) URL.
 */
url: string,
/**
 * Pixel width when known.
 */
width: number | null,
/**
 * Pixel height when known.
 */
height: number | null, };

export type VideoCodecFamilyDto = "h264" | "vp9" | "av1" | "other";

export type VideoCodecDto = {
/**
 * Normalized codec name.
 */
name: string,
/**
 * Recognized family.
 */
family: VideoCodecFamilyDto, };

export type AudioCodecFamilyDto = "aac" | "opus" | "vorbis" | "mp3" | "other";

export type AudioCodecDto = {
/**
 * Normalized codec name.
 */
name: string,
/**
 * Recognized family.
 */
family: AudioCodecFamilyDto, };

export type ContainerFamilyDto = "mp4" | "m4a" | "webm" | "other";

export type ContainerDto = {
/**
 * Normalized container name.
 */
name: string,
/**
 * Recognized family.
 */
family: ContainerFamilyDto, };

export type SourceFormatDto = {
/**
 * Extractor format identity.
 */
format_id: string,
/**
 * Source container.
 */
container: ContainerDto,
/**
 * Video codec when present.
 */
video_codec: VideoCodecDto | null,
/**
 * Audio codec when present.
 */
audio_codec: AudioCodecDto | null, };

export type CompatibilityWorkDto = "none" | "merge" | "video-transcode" | "audio-transcode" | "video-and-audio-transcode";

export type FormatOptionDto = { "kind": "mp3",
/**
 * Constant bitrate.
 */
bitrate_kbps: number,
/**
 * Selected source.
 */
source: SourceFormatDto, } | { "kind": "mp4",
/**
 * Source height.
 */
height: number,
/**
 * Source width.
 */
width: number | null,
/**
 * Frames per second.
 */
fps: number | null,
/**
 * Estimated combined size.
 */
estimated_size_bytes: string | null,
/**
 * Selected video-bearing source.
 */
video_source: SourceFormatDto,
/**
 * Selected audio-bearing source.
 */
audio_source: SourceFormatDto,
/**
 * Required compatibility work.
 */
compatibility: CompatibilityWorkDto, };

export type MediaInfoDto = {
/**
 * Eleven-character video identity.
 */
id: string,
/**
 * Canonical video URL.
 */
url: string,
/**
 * Bounded title.
 */
title: string,
/**
 * Uploader when present.
 */
uploader: string | null,
/**
 * Duration in milliseconds.
 */
duration_ms: string,
/**
 * View count when present.
 */
view_count: string | null,
/**
 * Upload date when present.
 */
upload_date: string | null,
/**
 * Validated thumbnails.
 */
thumbnails: Array<ThumbnailDto>,
/**
 * Engine-normalized choices.
 */
formats: Array<FormatOptionDto>,
/**
 * Bounded analyzer warnings.
 */
warnings: Array<string>, };

export type AnalyzeRequestDto = {
/**
 * Untrusted URL text.
 */
url: string, };

export type AnalyzeResponseDto = {
/**
 * Current IPC schema.
 */
schema_version: number,
/**
 * Engine-normalized media information.
 */
media: MediaInfoDto, };

export type OutputSelectionDto = { "format": "mp3", "quality": number } | { "format": "mp4", "quality": number };

export type EnqueueRequestDto = {
/**
 * Public single-video URL.
 */
url: string,
/**
 * Requested normalized output.
 */
output: OutputSelectionDto,
/**
 * User-facing destination directory.
 */
destination: string,
/**
 * Optional requested output stem.
 */
name: string | null, };

export type JobIdRequestDto = {
/**
 * `UUIDv7` job identity.
 */
job_id: string, };

export type JobStateDto = "queued" | "analyzing" | "downloading" | "merging" | "converting" | "paused" | "interrupted" | "completed" | "cancelled" | "failed";

export type JobStageDto = "analyzing" | "downloading" | "merging" | "converting" | "finalizing" | "completed" | "paused" | "cancelled" | "failed";

export type JobProgressDto = {
/**
 * Current stage.
 */
stage: JobStageDto,
/**
 * Completed work.
 */
completed: string,
/**
 * Known total.
 */
total: string | null,
/**
 * Percentage from zero through one hundred.
 */
percent: number | null,
/**
 * Transfer speed.
 */
bytes_per_second: string | null,
/**
 * Estimated seconds remaining.
 */
eta_seconds: string | null, };

export type JobErrorClassDto = "invalid-request" | "analysis" | "format-unavailable" | "destination-unavailable" | "filesystem" | "process" | "protocol" | "verification" | "internal";

export type JobFailureDto = {
/**
 * Stable classification.
 */
class: JobErrorClassDto,
/**
 * Bounded safe message.
 */
message: string, };

export type OutputAvailabilityDto = "not-applicable" | "present" | "missing";

export type FinalOutputDto = {
/**
 * Published output path.
 */
path: string,
/**
 * Published size.
 */
size_bytes: string,
/**
 * Requested output.
 */
output: OutputSelectionDto, };

export type JobActionDto = "pause" | "resume" | "cancel" | "retry" | "reveal" | "delete-history";

export type JobDto = {
/**
 * `UUIDv7` job identity.
 */
id: string,
/**
 * Canonical URL.
 */
canonical_url: string,
/**
 * Output selection.
 */
output: OutputSelectionDto,
/**
 * User-facing destination.
 */
destination: string,
/**
 * Optional requested name.
 */
name: string | null,
/**
 * Current state.
 */
state: JobStateDto,
/**
 * Current progress.
 */
progress: JobProgressDto | null,
/**
 * Persisted safe failure.
 */
error: JobFailureDto | null,
/**
 * Creation timestamp in epoch milliseconds.
 */
created_at_ms: string,
/**
 * Update timestamp in epoch milliseconds.
 */
updated_at_ms: string,
/**
 * Completion timestamp in epoch milliseconds.
 */
completed_at_ms: string | null,
/**
 * Explicitly started attempts.
 */
attempt_count: number,
/**
 * Verified output.
 */
final_output: FinalOutputDto | null,
/**
 * Current output availability.
 */
output_availability: OutputAvailabilityDto,
/**
 * Destination availability.
 */
destination_available: boolean,
/**
 * Whether the lifecycle state is terminal until an explicit retry.
 */
is_terminal: boolean,
/**
 * Engine-owned actions valid for this authoritative snapshot.
 */
available_actions: Array<JobActionDto>, };

export type JobActivityDto = { "event": "stage",
/**
 * New stage.
 */
stage: JobStageDto, } | { "event": "progress",
/**
 * New progress.
 */
progress: JobProgressDto, } | { "event": "warning",
/**
 * Bounded warning.
 */
message: string, };

export type JobEventEnvelopeDto = {
/**
 * IPC schema version.
 */
schema_version: number,
/**
 * Lossless monotonic sequence.
 */
sequence: string,
/**
 * `UUIDv7` job identity.
 */
job_id: string,
/**
 * Authoritative update timestamp in epoch milliseconds.
 */
timestamp_ms: string,
/**
 * Authoritative state.
 */
state: JobStateDto,
/**
 * Latest progress.
 */
progress: JobProgressDto | null,
/**
 * Terminal output when completed.
 */
result: FinalOutputDto | null,
/**
 * Terminal safe failure when failed.
 */
error: JobFailureDto | null,
/**
 * Optional transient activity.
 */
activity: JobActivityDto | null,
/**
 * Whether the updated lifecycle state is terminal until an explicit retry.
 */
is_terminal: boolean,
/**
 * Engine-owned actions valid for the updated snapshot.
 */
available_actions: Array<JobActionDto>, };

export type UpdatePreferenceDto = "notify" | "automatic" | "disabled";

export type SettingsDto = {
/**
 * Default destination.
 */
default_destination: string | null,
/**
 * Shared one-through-four concurrency.
 */
queue_concurrency: number,
/**
 * Managed update preference.
 */
update_preference: UpdatePreferenceDto,
/**
 * Last normalized output.
 */
last_output: OutputSelectionDto, };

export type DefaultDestinationUpdateDto = { "action": "unchanged" } | { "action": "clear" } | { "action": "set", "value": string };

export type UpdateSettingsRequestDto = {
/**
 * Default destination mutation.
 */
default_destination: DefaultDestinationUpdateDto,
/**
 * Replacement concurrency.
 */
queue_concurrency: number | null,
/**
 * Replacement update preference.
 */
update_preference: UpdatePreferenceDto | null,
/**
 * Replacement output default.
 */
last_output: OutputSelectionDto | null, };

export type DestinationSelectionDto = {
/**
 * Selected user-facing path, or `null` when cancelled.
 */
path: string | null, };

export type ActionResultDto = {
/**
 * Current IPC schema.
 */
schema_version: number, };

export type BootstrapStateDto = {
/**
 * IPC schema version.
 */
schema_version: number,
/**
 * Persistence and tool readiness.
 */
health: BootstrapHealthDto,
/**
 * Highest event sequence covered by this snapshot, encoded losslessly.
 */
last_event_sequence: string,
/**
 * Durable authoritative jobs.
 */
jobs: Array<JobDto>,
/**
 * Persisted engine settings when persistence is ready.
 */
settings: SettingsDto | null,
/**
 * Safe required-tool statuses.
 */
tools: Array<ToolStatusDto>,
/**
 * Recoverable startup diagnostic.
 */
diagnostic: IpcErrorDto | null, };
